const ACTIONS ={
  SET_KEYBOARD: 'SET_KEYBOARD',
  SET_KEYBOARD_LIST: 'SET_KEYBOARD_LIST',
  CREATE_KEYBOARD: 'CREATE_KEYBOARD',
  ADD_KEYBOARD_BUTTON : 'ADD_KEYBOARD_BUTTON',
  REMOVE_LAST_BUTTON : 'REMOVE_LAST_BUTTON',
  INPUT_TEXT_FIELD: 'INPUT_TEXT_FIELD',
  OUTPUT_TEXT: 'OUTPUT_TEXT'
}
export default ACTIONS;