//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keyboard.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DvrKey
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int KeyboardId { get; set; }
    
        public virtual DvrKeyboard DvrKeyboard { get; set; }
    }
}
